# Generated by Django 5.0.1 on 2024-01-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_colorvariant_sizevariant_product_colorvariant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvariant',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='ColorVariant',
            field=models.ManyToManyField(blank=True, to='products.colorvariant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='SizeVariant',
            field=models.ManyToManyField(blank=True, to='products.sizevariant'),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
