# Generated by Django 5.0.1 on 2024-01-09 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_colorvariant_price_alter_product_colorvariant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ColorVariant',
            new_name='color_variant',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='SizeVariant',
            new_name='size_variant',
        ),
    ]
